# Generated by Django 2.1 on 2018-08-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.TextField(max_length='50')),
                ('payment_description', models.TextField(max_length='30')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_avatar', models.ImageField(height_field='300', upload_to='', width_field='300')),
                ('full_name', models.TextField(max_length='50')),
                ('gender', models.CharField(max_length=10)),
                ('marital_status', models.TextField(max_length=10)),
                ('education_level', models.TextField(max_length='100')),
                ('field_of_study', models.TextField(max_length='100')),
                ('profession', models.TextField(max_length='100')),
                ('volunteer_type', models.TextField(max_length='50')),
                ('committee_type', models.TextField(max_length='50')),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length='15')),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
