# Generated by Django 2.1 on 2018-08-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20180809_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
