# Generated by Django 2.1 on 2018-08-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_payment_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Updates',
            new_name='Update',
        ),
    ]
